apiVersion: v1
description: Codefresh API Engine
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
keywords:
- codefresh
- kubernetes
- accounts-referrals
maintainers:
- email: davidl@codefresh.io
  name: David Levy
name: accounts-referrals
sources:
- https://github.com/codefresh-io/accounts-referrals
version: 0.0.3
