apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hermes.fullname" . }}
  labels:
    app: {{ template "hermes.name" . }}
    role: {{ template "hermes.role" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hermes.name" . }}  
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "hermes.name" . }}
        role: {{ template "hermes.role" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "hermes.fullname" . }} 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
          {{- if .Values.global.env }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}          
          - name: LOG_LEVEL
            value: {{ .Values.logLevel | quote }}
          - name: LOG_JSON
            value: {{ .Values.logJSON | quote }}
          {{- if ne .Values.logLevel "debug" }}
          - name: GIN_MODE
            value: release
          {{- end }}
          - name: NEWRELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
                key: newrelic-license-key
          - name: STORE_HOST
            value: "{{ .Release.Name }}-{{ .Values.redis.nameOverride }}"
          - name: STORE_PORT
            value: {{ .Values.redis.port | quote }}
          - name: STORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-{{ .Values.redis.nameOverride }}"
                key: redis-password
          - name: TYPES_CONFIG
            value: {{ default "/etc/hermes/type_config.json" .Values.types_config }}
          - name: PORT
            value: {{ .Values.service.internalPort | quote }}
          - name: CFAPI_URL
            {{- if .Values.cfapi.service }}
            value: "{{.Values.cfapi.protocol}}://{{.Values.cfapi.service}}:{{.Values.cfapi.port}}"
            {{- else }}
            value: "{{.Values.cfapi.protocol}}://{{.Release.Name}}-cfapi:{{.Values.cfapi.port}}"
            {{- end }}
          - name: CFAPI_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "hermes.fullname" . }}
                key: cfapi-token
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hermes
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 15
            failureThreshold: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
