{{ template "mailer.renderDeployment" (dict "imageTag" .Values.imageTag "Chart" .Chart "Release" .Release "Values" .Values "Files" .Files "Template" .Template) }}

{{- if .Values.global.istio.enabled }}
  {{- range $i, $value := .Values.global.istio.extraDeployments }}
---
    {{- range $host, $apps := $value }}
      {{- range $name, $a := $apps }}
        {{ $versionUnique := $host | replace "." "-" }}
        {{- if (eq $name "mailer") }}
{{ template "mailer.renderDeployment" (dict "version" $versionUnique "imageTag" $a.imageTag "appUrl" $host "Chart" $.Chart "Release" $.Release "Values" $.Values "Files" $.Files "Template" $.Template) }}
        {{- end }}
      {{- end }}
    {{- end }}

  {{- end }}
{{- end }}