{{- if  and .Values.rbacEnable .Values.rbacCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: ingress
# rules:
#   - apiGroups:
#       - ""
#       - "extensions"
#     resources:
#       - configmaps
#       - secrets
#       - endpoints
#       - ingresses
#       - nodes
#       - pods
#     verbs:
#       - list
#       - watch
#   - apiGroups:
#       - ""
#     resources:
#       - nodes
#     verbs:
#       - get
#   - apiGroups:
#       - ""
#     resources:
#       - services
#     verbs:
#       - list
#       - watch
#       - get
#       - update
#   - apiGroups:
#       - "extensions"
#     resources:
#       - ingresses
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - ""
#     resources:
#       - events
#     verbs:
#       - create
#       - patch
#   - apiGroups:
#       - "extensions"
#     resources:
#       - ingresses/status
#     verbs:
#       - update
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-ns
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - ingress-controller-leader-nginx
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-ns-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-ns
subjects:
  - kind: ServiceAccount
    name: ingress
    namespace: {{ .Release.Namespace }}
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: ingress-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: ingress
# subjects:
#   - kind: ServiceAccount
#     name: ingress
#     namespace: {{ .Release.Namespace }}
{{ end }}
