apiVersion: v1
description: Codefresh API Engine
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
keywords:
- codefresh
- kubernetes
- cfapi
maintainers:
- email: alexei@codefresh.io
  name: Alexei Ledenev
name: cfapi
sources:
- https://github.com/codefresh-io/cf-api
version: 0.2.3
