apiVersion: v1
description: Codefresh Payments
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
keywords:
- codefresh
- kubernetes
- payments
maintainers:
- email: alexei@codefresh.io
  name: Alexei Ledenev
name: payments
sources:
- https://github.com/codefresh-io/payments
version: 0.1.7
